{
    "name": "OpenG2P Process",
    "author": "Rohnak Agarwal",
    "version": "1.1",
    "category": "Project",
    "sequence": 10,
    "summary": "Wrapper on Openg2p Tasks.",
    "depends": [
        "openg2p_task",
    ],
    "description": "",
    "data": [
        "security/ir.model.access.csv",
        "views/openg2p_process_stage.xml",
        "views/openg2p_process_type.xml",
        "views/openg2p_process.xml",
        "views/action.xml",
        "views/menu.xml",
        "data/openg2p.process.stage.csv",
        "data/openg2p.process.type.csv",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
