{
    "name": "OpenG2P Task",
    "author": "Rohnak Agarwal",
    "version": "1.1",
    "category": "Project",
    "sequence": 10,
    "summary": "Guided navigation to tasks.",
    "depends": [],
    "description": "",
    "data": [
        "security/ir.model.access.csv",
        "views/openg2p_task_status.xml",
        "views/openg2p_task_role.xml",
        "views/openg2p_task_type.xml",
        "views/openg2p_task_subtype.xml",
        "views/openg2p_task.xml",
        "views/openg2p_tasks_widgets.xml",
        "views/openg2p_task_history.xml",
        "views/action.xml",
        "views/menu.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
